server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    tw.com.aidenmade.rescuehero: DEBUG

spring:
  application:
    name: RescueHero

  docker:
    compose:
      file: docker/compose.yaml
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/rescuehero
    username: ENC(xSJ2MhQnYNQroZAEIs2pRl/ADP14nKbZ2lHbjIXqSsOBWbimMr1oQRZaVIcCkueK)
    password: ENC(yZSSxKDGyuPRKuR5XXO5fnDRg3clpQcDOGBd1YBYtTsUxCr9WSftlJpETgsi5gUf)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  # 關閉 OSIV，避免 Entity 被意外修改

  sql:
    init:
      mode: always

  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/rescuehero
    redis:
      host: localhost
      port: 6379
      password: ENC(yZSSxKDGyuPRKuR5XXO5fnDRg3clpQcDOGBd1YBYtTsUxCr9WSftlJpETgsi5gUf)

# mongodb
MONGO_USER: ENC(xSJ2MhQnYNQroZAEIs2pRl/ADP14nKbZ2lHbjIXqSsOBWbimMr1oQRZaVIcCkueK)
MONGO_PASSWORD: ENC(yZSSxKDGyuPRKuR5XXO5fnDRg3clpQcDOGBd1YBYtTsUxCr9WSftlJpETgsi5gUf)