server:
  port: 8081
  servlet:
    context-path: /api
  # Make Spring honor X-Forwarded-* headers when behind nginx
  forward-headers-strategy: native

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    tw.com.aidenmade.rescuehero: DEBUG

spring:
  application:
    name: RescueHero

  threads:
    virtual:
      enabled: true

  docker:
    compose:
      file: docker/compose.yaml
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/rescuehero
    username: ENC(0IFRlsLDJzO5qD7O6Hp46mIrbGfEPe5qwH0pFK8Ph+eDA7F6wRwIVDLlOfHfFEZt)
    password: ENC(+A9Sit3tyOGTusnUMYjYjQbU1Ixb5oSe8rJTG700eD7SXkyGR7nNYNdQl4NhJpIf)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  # 關閉 OSIV，避免 Entity 被意外修改

  sql:
    init:
      mode: always

  data:
#    mongodb:
#      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/rescuehero
    redis:
      host: localhost
      port: 6379
      password: ENC(+A9Sit3tyOGTusnUMYjYjQbU1Ixb5oSe8rJTG700eD7SXkyGR7nNYNdQl4NhJpIf)

# mongodb
#MONGO_USER: ENC(0IFRlsLDJzO5qD7O6Hp46mIrbGfEPe5qwH0pFK8Ph+eDA7F6wRwIVDLlOfHfFEZt)
#MONGO_PASSWORD: ENC(+A9Sit3tyOGTusnUMYjYjQbU1Ixb5oSe8rJTG700eD7SXkyGR7nNYNdQl4NhJpIf)