server:
  port: 8081
  servlet:
    context-path: /api
  # Make Spring honor X-Forwarded-* headers when behind nginx
  forward-headers-strategy: native

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    tw.com.aidenmade.rescuehero: DEBUG

# SpringDoc OpenAPI (Swagger) 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false

spring:
  application:
    name: RescueHero

  threads:
    virtual:
      enabled: true

  docker:
    compose:
      file: docker/compose.yaml
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/rescuehero
    username: ENC(0IFRlsLDJzO5qD7O6Hp46mIrbGfEPe5qwH0pFK8Ph+eDA7F6wRwIVDLlOfHfFEZt)
    password: ENC(+A9Sit3tyOGTusnUMYjYjQbU1Ixb5oSe8rJTG700eD7SXkyGR7nNYNdQl4NhJpIf)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  # 關閉 OSIV，避免 Entity 被意外修改

  sql:
    init:
      mode: always

  data:
    mongodb:
      username: ENC(0IFRlsLDJzO5qD7O6Hp46mIrbGfEPe5qwH0pFK8Ph+eDA7F6wRwIVDLlOfHfFEZt)
      password: ENC(+A9Sit3tyOGTusnUMYjYjQbU1Ixb5oSe8rJTG700eD7SXkyGR7nNYNdQl4NhJpIf)
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@localhost:27017/rescuehero
    redis:
      host: localhost
      port: 6379
      password: ENC(+A9Sit3tyOGTusnUMYjYjQbU1Ixb5oSe8rJTG700eD7SXkyGR7nNYNdQl4NhJpIf)

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094  # 可以只寫一台，但如果這台掛了就會連不上，最好都寫上去

    consumer:
      group-id: rescuehero-group
      auto-offset-reset: earliest
      enable-auto-commit: false  # 關掉 Kafka 自己的 auto commit
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        session-timeout: 30s          # 對應 session.timeout.ms
        heartbeat-interval: 10s       # 對應 heartbeat.interval.ms
        max-poll-interval: 300s       # 對應 max.poll.interval.ms (5 分鐘)
        spring.json.trusted.packages: "tw.com.aidenmade.rescuehero.domain.chat"
        spring.json.value.default.type: "tw.com.aidenmade.rescuehero.domain.chat.api.request.ChatMessageRequest"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      concurrency: 3     # 併發數
      ack-mode: record   # commit 模式 (record會自動commit、manual要自己commit、預設auto自動commit回報offset)

chat:
  kafka:
    group-id:
      chat: rescuehero-chat
    topics:
      group: rescuehero.chat.group
      team: rescuehero.chat.team

