upstream api_backend {
    least_conn;  # 或 round-robin 預設也可以
#     ip_hash;
    random;
#     server host.docker.internal:8081;
#     server host.docker.internal:8082;
    server host.docker.internal:8081 max_fails=3 fail_timeout=10s;
    server host.docker.internal:8082 max_fails=3 fail_timeout=10s;
    server host.docker.internal:8083 max_fails=3 fail_timeout=10s;
}

server {
    listen 443 ssl;
    server_name rescuehero;

    ssl_certificate /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    location /api/ {
        proxy_pass http://api_backend/api/;
        # Ensure websocket upgrade headers are passed
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Keep long-lived websocket connections open
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
        proxy_buffering off;
    }

    location / {
        proxy_pass http://host.docker.internal:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}