name: rescuehero
services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/certs:/etc/nginx/certs:ro
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:6.0
    environment:
      - 'MONGO_INITDB_DATABASE=rescuehero'
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
      - ./mongo/init:/docker-entrypoint-initdb.d:ro

  postgres:
    image: postgres:16-alpine
    environment:
      - 'POSTGRES_DB=rescuehero'
      - 'POSTGRES_USER=hero'
      - 'POSTGRES_PASSWORD=rescue'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--requirepass", "rescue"]
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

  kafka-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'   # 對外連線用
      - '29092:29092' # broker 內部用
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # 實際給 Kafka 自己看的 port，對應 ports 設定
      KAFKA_LISTENERS: PLAINTEXT_EXTERNAL://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      # 外部（localhost） & 內部（docker network） listener
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_EXTERNAL://localhost:9092,PLAINTEXT_INTERNAL://kafka-1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_EXTERNAL:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      # 副本數量：上限是broker數量，但正式環境 FACTOR 建議至少 3，ISR 至少 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      # 關閉自動建立 topic
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - kafka-1-data:/var/lib/kafka/data

  kafka-2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-2
    depends_on:
      - zookeeper
    ports:
      - '9093:9092'   # 第二台 broker 對外 port 用 9093
      - '29093:29092' # 第二台 broker 內部 port 映射
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # 若在 docker 起兩台 kafka 且 ports 設定內外不同(如:9093:9092)的話就必須指定 KAFKA_LISTENERS，
      # 否則 kafka 會搞錯自己內部是聽什麼 port，預設是會以外部 port(9093) 來當作自己監聽的 port，但其實 ports 設定是連到 9092
      # 當然也可以直接設定 ports: 9093:9093，但是不建議
      KAFKA_LISTENERS: PLAINTEXT_EXTERNAL://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      # 注意 INTERNAL host 換成 kafka-2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_EXTERNAL://localhost:9093,PLAINTEXT_INTERNAL://kafka-2:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_EXTERNAL:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      # 副本數量：上限是broker數量，但正式環境 FACTOR 建議至少 3，ISR 至少 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      # 關閉自動建立 topic
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - kafka-2-data:/var/lib/kafka/data

volumes:
  mongodb-data:
  postgres-data:
  redis-data:
  zookeeper-data:
  zookeeper-logs:
  kafka-1-data:
  kafka-2-data:
